/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: artfletch (https://sketchfab.com/artfletch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chinese-bridge-ornament-b254f3156a4d45fb841faf6c277719ce
Title: Chinese Bridge Ornament
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import bridgeScene from '../assets/3d/bridge.glb'

const Bridge = (props) => {
  const { nodes, materials } = useGLTF(bridgeScene)
  return (
    <group {...props} dispose={null}>
      <group position={[-8, -11, -14]} rotation={[0.94, 0, -0.5]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.FishTankBridge01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.FishTankBridge01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.FishTankBridge01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.FishTankBridge01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.FishTankBridge01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.FishTankBridge01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.FishTankBridge01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.FishTankBridge01}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/bridge.glb')
export default Bridge;
