/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ebmclachlan (https://sketchfab.com/ebmclachlan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/yard-grass-3a67e76decc849c694c228eb590a9902
Title: Yard Grass
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Grass = (props) => {

  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/yard_grass.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="gmabccleanermaterialmergergles">
            <group name="Object_2" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Object_3">
                <group name="MorphMainGroup">
                  <mesh
                    name="gm"
                    castShadow
                    receiveShadow
                    geometry={nodes.gm.geometry}
                    material={materials.material}
                    morphTargetDictionary={nodes.gm.morphTargetDictionary}
                    morphTargetInfluences={nodes.gm.morphTargetInfluences}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/yard_grass.glb')
export default Grass;
