/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Rainer Laufer (https://sketchfab.com/drt666)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/samurai-statue-f3cb3244e35844a78fb393b9244061a7
Title: Samurai Statue
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import samuraiScene from '../assets/3d/samurai.glb'

const Samurai = (props) => {
  const { nodes, materials } = useGLTF(samuraiScene)
  return (
    <group {...props} dispose={null} position={[2, -8, -7]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials['Material.001']}
        rotation={[-Math.PI / 2, 0, -.5]}
      />
    </group>
  )
}

useGLTF.preload('/samurai_statue.glb')
export default Samurai;
