/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Terrie Simmons-Ehrhardt (https://sketchfab.com/terrielsimmons)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sand-at-sunset-beach-1ac0847acae44ffe9c3783be28e82bcf
Title: Sand at Sunset Beach
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import sandScene from '../assets/3d/sand.glb'

const Sand = (props) => {
  const { nodes, materials } = useGLTF(sandScene)

  return (
    <group {...props} dispose={null}>
      <group position={[0, -1, -1]} rotation={[0.233, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.material0000}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.material0000}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.material0001}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/sand.glb')

export default Sand
